### ISSUE TITLE
Broken Chat

### ISSUE THREAD

**Issue by InfinityAspire** [ProtocolSupport/ProtocolSupport#1060]
When using versions lower than 1.13.2, chat simply does not send. Plugins such as PurpleIRC are still somehow able to pick it up, but this was not an issue on the last build we were on [363].
No output from /ps debug. Chat plugin we're using is VentureChat but again, this was not an issue on the last build of ProtocolSupport we were on.
* ProtocolSupport version: Build 376
* Server version: PaperSpigot 1.13.2

**Comment by Shevchik** [comment]
Remove all plugins and try again.

**Comment by InfinityAspire** [comment]
Unfortunately I'm unable to do so as it's a production server. I'll work through builds and see which works

**Comment by InfinityAspire** [comment]
@Shevchik would there be a reason chat messages from older clients would not be picked up by this listener?
[https://i.imgur.com/58hnJ4l.png](https://i.imgur.com/58hnJ4l.png)

**Comment by Aust1n46** [comment]
Plugin messaging does not work with ProtocolSupport.  Chat is not showing up because the plugin messages being sent to the BungeeCord proxy are not being received and thus is unable to be sent back to the servers and displayed to the players.

Had a similar issue with ViaVersion where the pluginmessaging channel was being renamed to have "ViaVersion" in the name which messed up the listener.  Fixed this by just accepting messages from the "ViaVersion" channel.  With ProtocolSupport I'm receiving no data all on the BungeeCord proxy end listening for all channels.

**Comment by Shevchik** [comment]
The venturechat: won't be accepted by ps as a 1.13 formatted channel since it uses empty channel name. So it will be transformed to l:venturechat.

**Comment by Shevchik** [comment]
You can always attempt to fix that by fixing the regular expression there
https://github.com/ProtocolSupport/ProtocolSupport/blob/226607ef45a7656f5812697947eb14d58b0ca227/src/protocolsupport/protocol/typeremapper/legacy/LegacyCustomPayloadChannelName.java#L56

**Comment by Aust1n46** [comment]
I tested the new change and it works fine.  You can close this.  Thanks for being quick!
