### ISSUE TITLE
Statistics in 1.13.2 & lower

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#1138]
loading statistics in 1.13.2 kicks the client:
"Internal Exception: io.netty.handler.codec.DecoderException: java.lang.NullPointerException"

1.12.2 & lower remain stuck at the downloading statistics screen.

Note: I am aware 1.6 & lower will not be fixed, I'm not talking about these versions.

**Comment by Shevchik** [comment]
We do not support sending statistics at all. Might insert a stub so client at least leaves that screen tho.

**Comment by MasterDash5** [comment]
Should probably update the readme, as currently it only says 1.6 & lower have the issue

**Comment by Shevchik** [comment]
To make client leave screen you need to send all stats that were present on those versions. But you can leave that screen by pressing ESC so it's not that a big problem.
The kick reason for 1.13 is because 1.14 has statistics that didn't exist 1.13

So i decided to implement statistics sending only for latest version, and do not implement anything (even stubs for others). Of course if somebody is willing to do this, i can always accept the pull request, but i can't justify spending any time on this.

I will update README to reflect this.
