### ISSUE TITLE
Tab completion/suggestion issue

### ISSUE THREAD

**Issue by Sukram28** [ProtocolSupport/ProtocolSupport#1172]
**Report**
On 1.13+ Servers 1.4.7-1.12.2 Clients can see all hidden command suggestions.

This is a huge safety issue. Many Plugin developers don't know how to hide command suggestions. 1.12- Clients just need to type /[Tab] and get an entire list of all plugins that the server uses. Commands which they shouldn't see and probably can't even execute. Those Clients get a list of AntiCheat Plugins and can simply use specific hackclients which can handle those anticheat plugins and even worse: With all plugin information they can copy Server or look for specific things which aren't blocked, like some dupe exploits which can be prevented by some plugins or AFK-Detectors and so on.

At least it should be possible to prevent command suggestions for 1.12- Clients if the spigot option: `tab-complete: -1` is set.

There is no way to fix this manual. I've tried almost everything, like 
- canceling the `PacketType.Play.Client.TAB_COMPLETE PacketEvent`,
- canceling the `TabCompleteEvent`
- clearing the commandlist on the `PlayerCommandSendEvent`
- modifying the spigot.yml config option: `tab-complete: -1`

**How to recreate**

Use a 1.13-1.14 Server with ProtocolSupport.
Add a plugin which implements a Listener with @EventHandler public void onTab(PlayerCommandSendEvent e) { e.getCommands().clear(); }
Join the Server with a 1.12 Client and type in chat / + [TAB]

**ProtocolSupport version (/ps buildinfo)**
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.04.09 at 18:42:11 MSK, buildhost: build.true-games.org, buildnumber: 377)

**Server version**
paper-1.13.2, paper1.14.4, spigot-1.13.2, spigot 1.14.4 latest versions

**Comment by Shevchik** [comment]
ProtocolSupport only transforms the protocol format.
The server responds to client tab complete request. I have no idea why tab complete option doesn't work for it, nor do i care.

**Comment by Sukram28** [comment]
mhm ok thank you :/

**Comment by PinkLolicorn** [comment]
> ProtocolSupport only transforms the protocol format.

Looks like there are additional steps needed to support tabcomplete on 1.13+ servers. Found this issue because I experience this problem also.

1.15 client receives completions for /* in [DeclareCommands](https://github.com/ProtocolSupport/ProtocolSupport/blob/0198f51f763ed51438004a02eaba2966d546fdb3/src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_13_14r1_14r2_15/DeclareCommands.java), but for 1.12 and lower version client behavior is that client sends TabComplete even for /*. Clients from 1.13 and up do not send tab complete packets until first argument (space) begins.

With this in mind, plugins written for 1.13 and newer versions may not respond properly to TabComplete packets for "/x", but only for "/x ", which is first argument beginning. Also, I think that Bukkit/Spigot is ignoring your translated stuff, because no event is triggered. Still, thus I don't understand from where comes the reply as there is no TabCompleteEvent nor CommandListSendEvent when using tab on "/" from 1.12.2 client.

The idea is that ProtocolSupport should save lists from DeclareCommands packets for older clients and respond with them when TabComplete for "/" or "/x" (filtering matches) is sent.

**Comment by Shevchik** [comment]
That 1.13+ can actually send the same < 1.12 clients can do, you just need to modify it. It's  not the ProtocolSupport job to fix that.

**Comment by PinkLolicorn** [comment]
The problem is that there is no event triggered for it, so plugins can't do this.

**Comment by Shevchik** [comment]
Then can by intercepting packets. Still it's not a protocolsupport problem.

**Comment by PinkLolicorn** [comment]
Looks like ProtocolLib cannot handle this outgoing TAB_COMPLETE packet. Starts triggering at the first argument. Can you explain how exactly do ProtocolSupport handles this? I looked into the code but it is a bit complex because of how many versions it supports.

**Comment by Shevchik** [comment]
https://github.com/ProtocolSupport/ProtocolSupport/blob/master/src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_9r1_9r2_10_11_12r1_12r2/TabComplete.java

https://github.com/ProtocolSupport/ProtocolSupport/blob/master/src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleTabComplete.java

**Comment by PinkLolicorn** [comment]
@Shevchik, I think missing slash may be a problem.

![image](https://user-images.githubusercontent.com/44551064/71359620-5d0d7180-258d-11ea-90b8-eb9944898a1a.png)

I typed "/whis\*tab*" and it looks the same if I would type "whis\*tab*".

**Comment by PinkLolicorn** [comment]
ProtocolLib actually started triggering, but my client gets packets without / in response. Not sure but I think it is related to this but in opposite side.
