### ISSUE TITLE
ProtocolSupport & WorldEditCUI

### ISSUE THREAD

**Issue by iBars** [ProtocolSupport/ProtocolSupport#1186]
Mod WorldEditCUI for WorldEdit selection visualisation on client side has only version for Minecraft 1.12.2. And ProtocolSupport is one in the world thing which can provide WorldEditCUI support to use it on Spigot/Bukkit 1.13-1.14.x+... But it's not working. When I join 1.14.4 server with ProtocolSupport, WorldEditCUI don't work. It don't show any selection visualisation. But ProtocolSupport is unreplaceable thing in the world which able to provide bridge between WorldEditCUI (1.12.2) <-and-> Spigot/Bukkit (1.13-1.14.x+). Please, make it possible to use WECUI from MC 1.12.2 on latest MC servers. Thank you!

**Comment by iBars** [comment]
Also write about this advantage in plugin page on SpigotMC/BukkitDev, when you done

**Comment by Shevchik** [comment]
The WorldEditCUI mod does have a 1.12.2 version for worldedit 7, which uses modern channel format, so it works with ProtocolSupport. WorldEditCUI also exists for modern versions of minecraft. The API for custom payload transformer itself will be added soon, but it is pointless to implement the legacy WorldEditCUI support for worldedit 6, because worldedit 6 won't even run properly on latest server.
