### ISSUE TITLE
Bug with Fabric API in 1.16 (sending invalid minecraft:climbable tags)

### ISSUE THREAD

**Issue by fantahund** [ProtocolSupport/ProtocolSupport#1255]
PS Version : buildnumber: 504
Server Version:
[04:10:49 INFO]: This server is running Paper version git-Paper-29 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[04:10:49 INFO]: Checking version, please wait...
[04:10:49 INFO]: Previous version: git-Paper-27 (MC: 1.16.1)
[04:10:49 INFO]: You are running the latest version

Can you fix this?
https://github.com/FabricMC/fabric/issues/859

**Comment by Shevchik** [comment]
Currently protocolsupport doesn't really have any way to map modern string ids to leagcy string ids. Creating such registry is possible (especially since a part of it already exists in resource generator in order to upgrade mojang legacy blocks/items data to latest one for mappings generation purposes), but since it doesn't affect vanilla the priority of implementing this is low.

**Comment by Shevchik** [comment]
This is probably fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/691f18e8113b11471abbece76a4b28f8ba1cef76, but needs verifying.
