### ISSUE TITLE
Holograms armorstand visible. [1.11.2]

### ISSUE THREAD

**Issue by FlamestoN** [ProtocolSupport/ProtocolSupport#347]
Hello, when i'm using ProtocolSupport, i can see armorstands on Holograms (HolgraphicDisplays)

ProtocoSupport: #654
Spigot:  git-Spigot-7d78b81-f9e0440 (MC: 1.11.2)

Screens:
http://snap.ashampoo.com/4sfcSMLX
http://snap.ashampoo.com/Tn7WMzLd

**Comment by BiGUNMAN** [comment]
Update to build #654, this has already been fixed.

**Comment by FlamestoN** [comment]
I sad what i ALREADY use build #654 and this is not been fixied, you see?

**Comment by BiGUNMAN** [comment]
Build 654 isn't the most recent one.

**Comment by FlamestoN** [comment]
Really?
What is this then? http://build.true-games.org/job/ProtocolSupport/lastBuild/

**Comment by BiGUNMAN** [comment]
Eh,  I thought you originally said you were using build #649. Update your
plugins, I also had this issue but the latest build resolved it, so there
might be another plugin causing this unless you tried removing protocol
support and noticed that the issue was fixed.

**Comment by FlamestoN** [comment]
What plugins should I update?
I use the last spigot, last protocolsupport, and last holograms displays.

I'm deleting ProtocolSupport and without him all is fine.
Problem in ProtocolSupport.
You didn't even look at the screenshots, which I have attached. Why do you answer?!

**Comment by BiGUNMAN** [comment]
Yes, I did look at them. I had an identical problem with an older build.

On Dec 30, 2016 10:46 AM, "Dmitry" <notifications@github.com> wrote:

What plugins should I update?
I use the last spigot, last protocolsupport, and last holograms displays.

I'm deleting ProtocolSupport and without him all is fine.
Problem in ProtocolSupport.
You didn't even look at the screenshots, which I have attached. Why do you
answer?!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ProtocolSupport/ProtocolSupport/issues/347#issuecomment-269807359>,
or mute the thread

**Comment by Brokkonaut** [comment]
I can not confirm this bug. Tested on Paper 1008 +HolographicDisplays v2.2.3 + ProtocolSupport 654 and Vanilla 1.11.2 minecraft client - everything is fine
