### ISSUE TITLE
GlowStone.

### ISSUE THREAD

**Issue by maxim19116** [ProtocolSupport/ProtocolSupport#354]
Can you add in the ProtocolSupport support GlowStone kernel(https://github.com/GlowstoneMC/Glowstone), I will be very grateful for the help.

**Comment by gdude2002** [comment]
As one of the admins of the Glowstone project, I'd like to just add to this ticket by saying that we're happy to help you with this implementation as far as is reasonable.

There's a Discord invite URL in our README - feel free to come and chat to us there if any help is required.

**Comment by Shevchik** [comment]
Support of other versions requires an abstraction layer that can select between server implementations. But that one at least is not that hard due to i actually made a lot of changes to use a lot less nms.
But the other one issue is that other server implementation needs to have tge same netty version as spigot does and the same network pipeline.

**Comment by gdude2002** [comment]
So you guys are directly working against Netty? Alright.

We're actually using flow-network, which builds against Netty 4.1.0.CR3. I'm not sure what Spigot is using, though.

Would it be out of the question to maintain a second source set for glowstone-specific stuff, or is that even necessary?

**Comment by Shevchik** [comment]
Yes, packet transformation layer directly uses netty buffers and decoders and expects a special layout of the pipeline.

Maintaining a separate tree for glowstone implementation is a big no, mainly because i will always forget to update it.

**Comment by gdude2002** [comment]
OK, so we need the abstraction layer.

Would you perhaps be able to create such a layer as an API and let us take care of the implementation details?

**Comment by mastercoms** [comment]
Hi, I'm the project lead of Glowstone. 

It would be amazing if we could support your plugin, as many of our users have requested this feature. Although I'm not familiar with Spigot's networking, I think it's safe to say that it is much different from our pipeline and a lot of abstraction is necessary.

Thus, I think it would be best if the Glowstone project created an abstraction layer, but we would need your guidance for what such a layer should expose and for the overall flow/design of it.

**Comment by Shevchik** [comment]
Okay, protocolsupport needs a way to add some handlers to channel pipeline:
1) ProtocolSupport replaces splitter/prepender for < 1.7
2) Adds encoder_transformer that is positioned between encoder and compressor
3) Adds decoder_transformer that is positioned between decompressor and decoder.
4) Also there is additional handler before real packet handler to provide packet API, but i can use existing packet API if glowstone has one.

Also protocolsupport provides some APIs which require rewriting packet handlers or adding api directly to glowstone:
1) Connection open event (fired when netty channel is created)
2) Connection close event (fired when netty channel closes)
3) Connection handshake event (fired after receiving http://wiki.vg/Protocol#Handshake), it allows changing remote address)
4) PlayerLoginStartEvent (fired after receiving http://wiki.vg/Protocol#Login_Start, also a separate thread pool used for processing this event (not main thread, and not netty threads)), this one allows switching between online/offline mode event for this player, force changing it's uuid, etc...
5) PlayerPropertiesResolveEvent (fired after receiving or not receiving profile properties from mojang session server, also a separate thread pool used for processing this event (not main thread, and not netty threads)), it allows changing profile properties like skins.
6) PlayerLoginFinishEvent - this is the hardest event to implement. It is fired after player finishes login, but before server moves player to world ( also a separate thread pool used for processing this event (not main thread, and not netty threads)). This events switche client protocol state to play so it accepts play packets and maintains it until event is complete by resetting server readtimeout handler and sending client http://wiki.vg/Protocol#Plugin_Message_.28clientbound.29 packet with a tag that doesn't exist in vanilla minecraft (this allows for infinite wait times on logging in screen, or doing other tricks like spawning player in fake world because player client accepts all play state packets).
7) PlayerSyncLoginEvent (fired before PlayerLoginEvent), this event is almost the same as PlayerLoginEvent.
8) ServerPingResponseEvent (fired after ServerListPingEvent), it allows changing protocol description and version.
9) ItemStackWriteEvent (fired when writing any ItemStack to client), it has a pretransformed itemstack and posttransformed one and allow changing posttransforming one.
All events above except ItemStackWriteEvent has access to a Connection, it allows getting player remote InetSocketAddress, ProtocolVersion, getting NetworkManager (or whatever it is for), getting bukkit player instance if has one, adding packet send/receive listeners, and sending/receiving packets.

All other nms can be easilt abstracted away, because it is mainly used for reading/writing itemstacks and nbt and protocolsupport already has wrappers above them, so only glowstone implementation is needed for them.

**Comment by Shevchik** [comment]
Okay, i abstracted more things away, but still not all. But people who are familiar with glowstone implementation can start making pull requests for implementing things marked as
// TODO: implement for glowstone

**Comment by maxim19116** [comment]
Thanks!

**Comment by Shevchik** [comment]
Only a few things left to do,

**Comment by maxim19116** [comment]
Yay thanks

**Comment by Shevchik** [comment]
GlowStone support is fully implemented now
