### ISSUE TITLE
Lots of fixes and new features

### ISSUE THREAD

**Issue by Roadhog360** [ProtocolSupport/ProtocolSupport#449]
Get ready, I've made a lot of cool suggestions and fixes for you!
Here we go.

Starting off, you should make it so whenever someone has an item from a newer version of the game, like a 1.7 player holding, say, Red Nether Brick would have that item be named Red Nether Brick. There would be no formatting in the name, thus making it italic, so people can more easily tell that whatever item they are holding is from a newer version.

Tipped arrows emit particles of their respective potion on versions that do not have tipped arrows.

An option for servers to require older versions to use Lapis Lazuli to enchant. You could make it take directly from the inven depending on level. Option to disable since some servers have lapis already in the enchant table, thus removing the need for having this feature on.

Next is an attack delay bar. Some servers have the attack delay disabled, so this should be a config option. Make it so, in the boss bar, it will fill up after you swing an item, full being you can attack again at full force, mimicking the attack delay indicator bars from 1.9 and above, so 1.8 and older users can see their attack delay.

Next, a fix for levitation. Older clients should have it so they get repeated upwards momentum to mimic levitation.

Next off is a way to configure what replacement blocks and items are. For example, Magma Block is Netherrack on older versions, that is unfair to me, and so with this feature, I could configure Magma Block to show up as something else on older clients. 

Next off is support for 1.4.x, since only 1.4.7 is supported for whatever reason.

Almost done. Next could be Et Futurum support. If the mod is detected, blocks, mobs, and other assets from that mod are used if available. Config option to turn this off, and also config option to require the mod to use 1.7. First option overrides.

Finally, armour stands should appear as Skeletons that do not move on 1.7 and lower. As expected, click the head of the Skeleton to put a helmet there, click the legs to put leggings, etc.

**Comment by Roadhog360** [comment]
What do you think? I feel if you added my suggestions and fixes, this plugin could be a lot better, and make it easier for older versioned users to understand what the heck they're doing. If I missed anything, tell me.

Also, another thing. As with a way to put lapis in the Enchant Table, there should also be a way to put Blaze Powder in the Brewing stand.

Alright, that is all.

**Comment by Roadhog360** [comment]
Sorry for triple post, but I almost forgot. There should be a way to see holograms in older kversions as well.

Additionally, be sure the placeholder config supports data values to ensure people can configure what ProtocolSupport shows to their older users is usable at its fullest potential.

**Comment by jojoe77777** [comment]
> There should be a way to see holograms in older versions as well.

https://github.com/ProtocolSupport/ProtocolSupportLegacyHologram

> there should also be a way to put Blaze Powder in the Brewing stand.

https://github.com/ProtocolSupport/ProtocolSupportBrewingStandFuel

**Comment by MrPowerGamerBR** [comment]
> Starting off, you should make it so whenever someone has an item from a newer version of the game, like a 1.7 player holding, say, Red Nether Brick would have that item be named Red Nether Brick. There would be no formatting in the name, thus making it italic, so people can more easily tell that whatever item they are holding is from a newer version.

Shevchik won't do that, I already suggested this before and he didn't want to do it, also, you can do that with ProtocolSupport's API. (or by just editing the source code, I already done that before and it wasn't hard)

> An option for servers to require older versions to use Lapis Lazuli to enchant. You could make it take directly from the inven depending on level. Option to disable since some servers have lapis already in the enchant table, thus removing the need for having this feature on.

https://github.com/ProtocolSupport/ProtocolSupportEnchantingTable

> Next off is a way to configure what replacement blocks and items are. For example, Magma Block is Netherrack on older versions, that is unfair to me, and so with this feature, I could configure Magma Block to show up as something else on older clients.

Blocks are replaced with something that matches the hardness value, if you replace with something with an lower/higher hardness value, you won't be able to break it in Survival (Anti-Cheat stuff).

> Next is an attack delay bar. Some servers have the attack delay disabled, so this should be a config option. Make it so, in the boss bar, it will fill up after you swing an item, full being you can attack again at full force, mimicking the attack delay indicator bars from 1.9 and above, so 1.8 and older users can see their attack delay.

ProtocolSupport shouldn't handle that, just create a plugin for it instead of bloating ProtocolSupport's source code.

> Next off is support for 1.4.x, since only 1.4.7 is supported for whatever reason.

Shevchik isn't adding support for older versions anymore, if you want it, add it yourself. (Also, who the fuck uses versions older than 1.4.7?)

> Almost done. Next could be Et Futurum support. If the mod is detected, blocks, mobs, and other assets from that mod are used if available. Config option to turn this off, and also config option to require the mod to use 1.7. First option overrides.

Again, ProtocolSupport shouldn't handle that.

> Finally, armour stands should appear as Skeletons that do not move on 1.7 and lower. As expected, click the head of the Skeleton to put a helmet there, click the legs to put leggings, etc.

Another thing that should be done in a plugin and not in ProtocolSupport.

Also, you can't check where the player clicked on an entity, you can only know that he clicked on the entity, not WHERE.

**Comment by Shevchik** [comment]
^

**Comment by Roadhog360** [comment]
To check where, just put four bats inside the entity or the angle the player is looking. Simple.

And how can I just edit the code? I don't know how to code, please don't assume everyone can.

**Comment by MrPowerGamerBR** [comment]
@Roadhog360 then ask someone to do that for you.

Also, 
> To check where, just put four bats inside the entity or the angle the player is looking. Simple.

I think the bat hitbox is smaller than the skeleton hitbox, so this wouldn't work, also, players would be able to see the entity's invisible particles. (you could use a slime for that like how interactive holograms works but still, this shouldn't be handled by ProtocolSupport)

**Comment by 7kasper** [comment]
@MrPowerGamerBR @Roadhog360 I think it is entirely doable that way, perhaps even fun. It really should be its own plugin though. For those that really need armour stands.

**Comment by MrPowerGamerBR** [comment]
@7kasper yeah it isn't impossible (I tried doing that before with a plugin, never finished it because I didn't have enough knowledge about Java at the time (it was 2015 okay?)) but it really shouldn't be added to ProtocolSupport, ProtocolSupport is already big as it is, adding more features will just slow down the update process when Mojang releases a new version.

**Comment by Roadhog360** [comment]
When I get home, I'll be explaining why I think some of these are essential and bog down the plugin's usability.

**Comment by MrPowerGamerBR** [comment]
@Roadhog360 but even with explanations, I doubt they would be implemented in ProtocolSupport.

> An option for servers to require older versions to use Lapis Lazuli to enchant. You could make it take directly from the inven depending on level. Option to disable since some servers have lapis already in the enchant table, thus removing the need for having this feature on.

> Also, another thing. As with a way to put lapis in the Enchant Table, there should also be a way to put Blaze Powder in the Brewing stand.

> There should be a way to see holograms in older versions as well.

Already possible with plugins.

> Next off is a way to configure what replacement blocks and items are. For example, Magma Block is Netherrack on older versions, that is unfair to me, and so with this feature, I could configure Magma Block to show up as something else on older clients.

Triggers Mojang's Anti-Cheat mechanism, causes issues when breaking "replaced" blocks with hardness value different than the original block.

> Next off is support for 1.4.x, since only 1.4.7 is supported for whatever reason.

Shevchik isn't adding support to older versions anymore, if you want older versions, you need to add it yourself. (And, if I recall correctly, it wasn't Shevchik that added support to 1.4.7)

> Next is an attack delay bar. Some servers have the attack delay disabled, so this should be a config option. Make it so, in the boss bar, it will fill up after you swing an item, full being you can attack again at full force, mimicking the attack delay indicator bars from 1.9 and above, so 1.8 and older users can see their attack delay.

Will lag the server a LOT, you will need to check the attack delay EVERY TICK just to send the bossbar update, so...

___

Also, you will need to know that ProtocolSupport DOESN'T send packet at will, it just TRANSLATES packets from newer versions to a format compatible with older versions, so this:

> Next, a fix for levitation. Older clients should have it so they get repeated upwards momentum to mimic levitation.

> Tipped arrows emit particles of their respective potion on versions that do not have tipped arrows.

> Finally, armour stands should appear as Skeletons that do not move on 1.7 and lower. As expected, click the head of the Skeleton to put a helmet there, click the legs to put leggings, etc.

are impossible to do.

**Comment by Shevchik** [comment]
There is an api for most of that inside protocolsupport. I will not add any non essential code to protocolsupport because you cant replace it on the fly.

**Comment by 7kasper** [comment]
@Roadhog360 I think we do understand your point. Besides being able to join, you want to be able to do stuff aswell.
For the better part protocol support is there for you too. As the core functions of minecraft haven't changed **that** much since 1.4.7 and the thing we do is rephrase packets.

We understand that many features could be faked in some kinds of ways, but the things that have nothing to do with protocol reprasing but instead implement entirely new functions or send packets when the server or client normally wouldn't to fake some functions are just the job of other plugins. (That can be really exstensive when implementing ProtocolSupport and some have already been made as @MrPowerGamerBR mentioned. If you want to do anything with that, because you can do alot using plugins now, help is always welcome, both with thinking and programming!)
 
_In the end ProtocolSupport is a plugin to support protocols and provide support for those protocols. That's that. Not fake features._

**Comment by Roadhog360** [comment]
But most is essential and I will soon explain why.

**Comment by Shevchik** [comment]
None of them are:

If the feature needs to be emulated in older versions and client won't crash if you don't change before ever trying to pull this to protocolsupport main codebase ask yourself these questions:
1) Can the feature be done purely at network level?
  - If yes - go to next question
  - If no - that won't be added unless client crashes because this feature is missing, or it's a really essentials feature such as walk, inventory, block, entity interaction and chat.
2) Can this feature can be moved to separate plugin by adding some API to protocolsupport
  - If no - add a feature request
  - If yes - that won't be added because it can be done in a separate plugin
3) How much does this feature decreases server performance?

After that you will have to wait for someone to pick it up, or implement it yourself.

**Comment by Roadhog360** [comment]
Just because it's possible to do with other plugins doesn't mean we should just completely leave out a feature of the game. It's not our responsibility to complete YOUR plugin.
I suggested features to make it more usable and you turned down every single one because someone else could do it, which is outright lazy and shows you're unwilling to complete your own plugin. Players on older versions can't use several things and I presented ways to fix that but since someone else could do it, you didn't. This is a legitimate reason to leave a bad SpigotMC rating; posting incomplete plugins, and I will should you not add a way to make armour stands usable on 1.7- or a way to have items named at the very least. I also don't want to install a bunch of third party plugins because you don't want to complete your own work.

"Blocks are replaced with something that matches the hardness value, if you replace with something with an lower/higher hardness value, you won't be able to break it in Survival (Anti-Cheat stuff)." -MrPowerGamerBR

Items don't have a hardness value. At least give me an option to configure THOSE at the very least, since I'd prefer to be able to control what's on my own server,

**Comment by MrPowerGamerBR** [comment]
```
Just because it's possible to do with other plugins doesn't mean we should just completely leave out a feature of the game. It's not our responsibility to complete YOUR plugin.
``´

And it also not Shevchik's responsibility to add features that he does not want in ProtocolSupport, after all, he created ProtocolSupport for his own server and just published it because he wanted to.

```
I suggested features to make it more usable and you turned down every single one because someone else could do it, which is outright lazy and shows you're unwilling to complete your own plugin.
```

Or maybe he doesn't want to bloat ProtocolSupport source code? After all, updating ProtocolSupport everytime Mojang releases a new update isn't easy at all, and bloating the code with features will make the update process a lot longer.

```
Also, on top of that, you only support the latest version when everyone might not want to update.

**Comment by MrPowerGamerBR** [comment]
```
Just because it's possible to do with other plugins doesn't mean we should just completely leave out a feature of the game. It's not our responsibility to complete YOUR plugin.
```

And it also not Shevchik's responsibility to add features that he does not want in ProtocolSupport, after all, he created ProtocolSupport for his own server and just published it because he wanted to.

```
I suggested features to make it more usable and you turned down every single one because someone else could do it, which is outright lazy and shows you're unwilling to complete your own plugin.
```

Or maybe he doesn't want to bloat ProtocolSupport source code? After all, updating ProtocolSupport everytime Mojang releases a new update isn't easy at all, and bloating the code with features will make the update process a lot longer.

```
Also, on top of that, you only support the latest version when everyone might not want to update.
```

Then use ViaVersion.

**Comment by Roadhog360** [comment]
"Then use ViaVersion."
Are you daft? ViaVersion doesn't do backwards compatibility.

**Comment by MrPowerGamerBR** [comment]
@Roadhog360 then don't use obsolete Minecraft versions ;)

**Comment by Roadhog360** [comment]
I'm on 1.11.2 though.

**Comment by MrPowerGamerBR** [comment]
Also, @Shevchik already explained why he doesn't want to add your suggestions, he isn't obliged to add anything to ProtocolSupport, after all, it is HIS plugin, and it is open source, do you want a feature? Add it yourself! 😄 

Also,
> Players on older versions can't use several things and I presented ways to fix that but since someone else could do it, you didn't.

Because all of the ways you said is impossible to implement them without some very nasty and hacky workarounds. (or can't be done purely on the networking side, again, ProtocolSupport CAN'T access things outside of the network thread because that's how Bukkit (and thread safety/synchronization) works.)

**Comment by Roadhog360** [comment]
How many times are you going to assume everyone can code and just say "Add it yourself."
If you're going to do that, at least tell me where or how you learned so I can learn and eventually come back to do it myself.

**Comment by MrPowerGamerBR** [comment]
@Roadhog360 asking me how I learned wouldn't help you at all, unless if you know portuguese. ^^

Anyway, the only one that can be done with code + PS API is the item renaming thingy (and maybe the block hardness change... I don't remember because I didn't use PS API since a long time ago but I suppose it is possible)

The rest needs a LOT of code, like the Armor Stand thingy for 1.7.X and SHOULDN'T be added to the PS Core, they should be handled in an external plugin (like holograms, enchantment tables, etc) so they don't bloat the PS core.

So... unless someone wants to code for you your armor stand support thingy (spoiler: Doing that isn't easy at all), then you are out of luck.

**Comment by DaMatrix** [comment]
@Roadhog360 if you really want to learn to code, do it the way I (and presumably most people have) did it and just spend hours reading through and testing out code on your own. Read articles. Watch videos. It's not that hard once you get the hang of it.

**Comment by gdude2002** [comment]
This issue has gone far beyond the bounds of what should be acceptable in a GitHub issue, or indeed on any bug tracker.

@Shevchik I recommend locking this issue.

**Comment by Roadhog360** [comment]
I agree that @Shevchik didn't fix simple issues with his plugin that pushed the issue as far as it was.

**Comment by MrPowerGamerBR** [comment]
@Roadhog360 because everything you asked isn't simple or easy to implement.

And, as you said before, you don't know how to develop things, you can't just say "oh he didn't do this and it was so simple to do", if it is simple, why don't you do it yourself?

**Comment by Roadhog360** [comment]
I guess you have a point. I may think some things are easier than they actually are. I've read code and can tell what some does, but I guess backwards compatibility in that case is easier said than done.
