### ISSUE TITLE
[14:16:53 INFO]: Feerko lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown mob network type id -1

### ISSUE THREAD

**Issue by 100petr** [ProtocolSupport/ProtocolSupport#540]
Hello, after updating the plug-in and the server to the latest version, the player throws out the message I mentioned above. I read https://github.com/ProtocolSupport/ProtocolSupport/issues/509 but there it was not solved.

**Comment by Shevchik** [comment]
The problem is on the server/other plugins side, not on protocolsupport.

**Comment by 100petr** [comment]
After removing protocolsupport it does not ..

**Comment by gdude2002** [comment]
ProtocolSupport does work; there is another plugin you have breaking it. This is not the first time we've seen this problem.

ProtocolLib is a likely contender.

**Comment by 100petr** [comment]
This is in turn necessary for the functionality of other plugins.

**Comment by MrPowerGamerBR** [comment]
If a plugin is doing this, then it is doing bad things that just doesn't disconnect the player because the vanilla setting is a bit more lenient than ProtocolSupport.

You should try to figure out what plugin is trying to spawn an invalid entity and report to the plugin creator this issue, because he shouldn't trying to spawn an entity with a invalid ID to the player. (after all, why he would do that? -1 isn't a valid entity!)

**Comment by 100petr** [comment]
I do not know what it can do, but when it comes to more people, it will probably be a plugin that is popular (often) I will try to get it and as soon as it does it again, I will start at protocollib as recommended, Maybe try essentialsx.

**Comment by MrPowerGamerBR** [comment]
@100petr also, while removing ProtocolLib may fix the issue, that doesn't mean that ProtocolLib is causing this issue because ProtocolLib is an API (you probably already knew that), if removing ProtocolLib fixes the issue, readd it and try removing every plugin that "broke" after you removing ProtocolLib until you find the right plugin that is causing the issue. :wink:

**Comment by Shevchik** [comment]
Also the common reason for this is BedwarsRel + Mypet, they both inject custom entities and BedwarsRel does it wrong.

**Comment by 100petr** [comment]
BW I do not have, and I have miniature pets ..
