### ISSUE TITLE
Nether issue

### ISSUE THREAD

**Issue by Lammendam** [ProtocolSupport/ProtocolSupport#644]
When player log out from server when he stay in the nether world - he got kicked when tries to log in next time.
Console wont print more info than this:

`Lammendam lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IndexOutOfBoundsException: readerIndex(16478) + length(2048) exceeds writerIndex(16688): UnpooledHeapByteBuf(ridx: 16478, widx: 16688, cap: 16688/16688)

When i clear player data from world folder (worldname\playerdata), the bug disappears, but if i logout from server staying in nether i would not have chance to login to server again untill my data will be cleared.

**Comment by Shevchik** [comment]
Enable debug and try again. Also try dumping dimension switch packets, because it looks like server sends invalid dimension or something like that.

**Comment by Shevchik** [comment]
Required info wasn't provided in 2 weeks, closing.

**Comment by Lammendam** [comment]
I thought that this problem you should resolve, not me, i've just say about bug and let you know about this.. But now i dont use your plugin because found an alternative.

**Comment by 7kasper** [comment]
@Lammendam You are always welcome to report bugs.
Now we definitely do not have infinity time on our hands and are not able to test everything especially not in every dimension :wink:
So if anyone has this issue, feel free to reopen it and provide the details Shev asked for so we can fix it.

**Comment by Shevchik** [comment]
Without debug info nothing can be done anyway with that. Most likely the server or some plugin sent chunk data with skylight, while player being in nether, which is not valid. While clients just skip those chunks (they won't load, or will decode wrong), protocolsupport doesn't allow invalid data (mainly because it's hard to support without adding tons of hacks to code, and even if we do it - people will start blaming those issues on us)
