### ISSUE TITLE
Position bug

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#666]
Something is wrong when player is in the water. Other players see him in another position than he is for real. For example they see him 10 block under his real position. The server is taking his position properly I think, he can place blocks normally, but can't be hit with an arrow etc.

**Comment by 7kasper** [comment]
Do you know what versions are affected and if this reproducable without other plugins?

**Comment by FurmigaHumana** [comment]
I dont know if this what he's talking about, but sometimes if you're building a bridge while sneaking your position will be far behind where is suposed to be, when you stop sneaking you do like a "quick jump" to the real position, never tried to search about this issue as it wont happen all the time, as far as I can tell is mostly random, but I think it has something to do with the relative movement being a little diferent in some versions while swiming/sneaking anything that slow you down.

**Comment by MasterDash5** [comment]
i've encountered this when pvping in 1.7. The opponent will sometimes be 1 block off from where they should be.

**Comment by KiwiTerra** [comment]
KiwiTerra's version (Minecraft Right) : Forge 1.7.10
da_chicken's version (Minecraft Left) : LabyMod 1.8.9

Spigot version : This server is running CraftBukkit version git-Spigot-3d850ec-809c399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
ProtocolSupport build: 188
BungeeCord : yes

Video : https://youtu.be/wp2AT4_FHk0

**Comment by FurmigaHumana** [comment]
Thank you for the video @KiwiTerra , this has been happening on my server for quite a while but never managed to figure out how to reproduce it, hopefully this helps the devs.. i worked around the issue by changing a few lines of code on the EntityTracker to send a "teleport" packet every 20 ticks instead of the relative movement thingy.

**Comment by KiwiTerra** [comment]
@FurmigaHumana Can you give me code please ? ^^

**Comment by spileur** [comment]
@FurmigaHumana Hello, what is the class that needs to be changed ?

**Comment by FurmigaHumana** [comment]
@KiwiTerra no code to share, i use a custom made spigot.

@spileur EntityTrackerEntry - inside the track method the only change needed is that every few ticks you should send a teleport packet (PacketPlayOutEntityTeleport) instead of the movement ones (PacketPlayOutRelEntityMove/PacketPlayOutRelEntityMoveLook/PacketPlayOutEntityLook). i do that every 20 ticks and seems to help.

**Comment by Shevchik** [comment]
Now we always override entity tracker and send absolute position, so this should be fixed (unless other plugin injects entity tracker too).
