### ISSUE TITLE
[Feature] Maven repo

### ISSUE THREAD

**Issue by DiscoverSquishy** [ProtocolSupport/ProtocolSupport#787]
Hey. I wanna start a project but I want to use this and add it into my pom.xml file although I need a repository it would be great if the team could add one unless I’m blind and there is one already.

**Comment by DaMatrix** [comment]
if the jars were to be downloaded automatically then you could use

https://jitpack.io/#ProtocolSupport/ProtocolSupport

but it doesn't work currently

**Comment by DiscoverSquishy** [comment]
Bump

**Comment by games647** [comment]
JitPack has an older version in their repository, but a lot have changed since. 

```xml
        <dependency>
            <groupId>com.github.ProtocolSupport</groupId>
            <artifactId>ProtocolSupport</artifactId>
            <!--4.25.dev-->
            <version>a4f060dc46</version>
            <scope>provided</scope>
        </dependency>
```

Default Gradle projects install their jar into `build/libs/project-name-version.jar`, but this project stores them into `target/project-name.jar`. Therefore JitPack cannot find it. Either Shevchik should install a maven repository server on the build server or we add a copy/symlink to the expected folder, so JitPack can find it.

**Comment by Shevchik** [comment]
I guess we can copy jar from build libs to target folder for now.

**Comment by Shevchik** [comment]
You can now use jitpack for that.
