### ISSUE TITLE
[RFC] Drop old versions support since 1.13

### ISSUE THREAD

**Issue by XakepSDK** [ProtocolSupport/ProtocolSupport#817]
The whole thing about multiversion was just to support last version and previous for migration purposes, but sometime this gone wrong and now everyone sits on 1.8(!) that is 4(!) years old!
I think, this is time for resolute actions to stop that circus with old versions.

**Comment by XakepSDK** [comment]
Same thread in viaversion: https://github.com/MylesIsCool/ViaVersion/issues/830
Same thread in bungeecord: https://github.com/SpigotMC/BungeeCord/issues/2419

**Comment by Ramu-2002** [comment]
No one cares it's not there fault that everybody uses 1.8

**Comment by Ramu-2002** [comment]
I use always latest version but some poeple don't like the new combat system everybody own opinion

**Comment by krusic22** [comment]
The whole point of ProtocolSupport is to provide a playable experience to all users. 
Some third world countries cannot play never version then 1.5.2/1.6.4 (due to Java or OpenGL).
Not everyone can update so you should also consider then not just yourself.

**Comment by XakepSDK** [comment]
@Ramu-2002 new combat system is **easily to disable** using attributes api
@krusic22 whole point of protocolsupport was to support newer/older versions for migration purposes.(wait for newer plugin version etc)

**Comment by krusic22** [comment]
That's mostly incorrect...

**Comment by hyndor** [comment]
It's time to drop it

**Comment by Shevchik** [comment]
While i do agree that version madness should stop, but unfortunately we can't do it anymore.
Many big servers have their own multiversion implementations or such hacks, so just droppping ps+via+bungee will result in smaller servers not being able to compete with big ones.
Also don't forget that anyone can just fork and continue the project, so you will have to convince every server owner and developer out there that multiversion isn't worth it.

**Comment by XakepSDK** [comment]
@Shevchik maybe just dropping all versions less than 1.13? Like start from scratch. It's impossible to make bedrock <-> 1.8 multiver. server.
Also, latest chunk/scoreboard(iirc) changes are nearly impossible to port. Biomes system is rewritten too, only you know, how hard to make this.

**Comment by MrPowerGamerBR** [comment]
@XakepSDK you totally missed the point of ProtocolSupport.

> whole point of protocolsupport was to support newer/older versions for migration purposes.(wait for newer plugin version etc), also, newer minecraft versions working faster and smoother than older, imo.

No, the point of ProtocolSupport is to keep your server updated (running the latest Minecraft version) while older clients can still connect to the server, there is various reasons why somebody didn't update to the latest version yet, some of them were mentioned by @krusic22.

Just because YOU want people to use the latest Minecraft version, doesn't mean that they will, go complain to Mojang for causing all the version stagnation, not projects that just want to keep their server up to date while still serving old players that can't update due to various reasons.

And chunks aren't that hard, Bedrock has a similar system used in Minecraft 1.13 and ProtocolSupport does support it just fine.
