### ISSUE TITLE
Chest is ender chest

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#877]
You see chest as ender chest. Tested on 1.12 and 1.8

**Comment by krusic22** [comment]
Working as intended.

**Comment by 7kasper** [comment]
Yes. This is intentional 😄 
Basically older clients have trouble rendering many chests next to eachother. This is why we remap to enderchest. Better see that then nothing at all! If you like to prevent players from placing double chests next to each other, but still have the old texture try this plugin: [https://www.spigotmc.org/resources/protocolsupportchestfix.59314/]

**Comment by DanielAlves123** [comment]
@krusic22 @7kasper @Shevchik Shouldn't chests be seen as chests and enderchest as enderchest?

**Comment by DanielAlves123** [comment]
@MrPowerGamerBR I would rather see chests as they are, I dont really need this placing large chests near each other feature.
